Google.Cloud.EntityFrameworkCore.Spanner.Tests/Migrations/SpannerMigrationSqlGeneratorTest.cs
Google.Cloud.EntityFrameworkCore.Spanner/Migrations/SpannerMigrationsSqlGenerator.cs

fix: should throw not supported exception while using default column value

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/TypeConversionTests.cs
README.md

Adds documentation and tests for type mapping and overflow.

docs: document and test type mapping and overflow

---

Google.Cloud.EntityFrameworkCore.Spanner/Extensions/TracerProviderExtension.cs
Google.Cloud.EntityFrameworkCore.Spanner/Google.Cloud.EntityFrameworkCore.Spanner.csproj
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRetriableTransaction.cs
Google.Cloud.EntityFrameworkCore.Spanner/Update/Internal/SpannerBatchExecutor.cs

Open telemetry tracing support for `SaveChanges` and `Commit` method.

feat: open telemetry tracing support

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/Migrations/MigrationSqlGeneratorTestBase.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/Migrations/SpannerMigrationSqlGeneratorTest.cs
Google.Cloud.EntityFrameworkCore.Spanner/Migrations/Internal/SpannerHistoryRepository.cs
Google.Cloud.EntityFrameworkCore.Spanner/Migrations/SpannerMigrationsSqlGenerator.cs

1. Create/Drop Unique Constraint
2. Create/Drop Primary key
3. `CREATE IF NOT EXISTS` style commands

fix: should throw NotSupportedException for unsupported spanner operation

---

README.md

Mark repository as __Preview__ version.

docs: document as preview release

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/MigrationTests/MigrationMockServerTests.cs

test: use assembly version instead of hard coded string

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/MigrationTests/MigrationMockServerTests.cs

Use build instead of revision in version number.

fix: use build instead of revision in version

---

Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/TransactionTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Samples/Snippets/StaleReadSample.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner/Extensions/QueryableExtensions.cs
Google.Cloud.EntityFrameworkCore.Spanner/Extensions/SpannerDbContextOptionsExtensions.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRetriableCommand.cs

Adds support for stale reads outside of (read-only) transactions.

feat: support single stale reads

---

Google.Cloud.EntityFrameworkCore.Spanner/Scaffolding/Internal/SpannerDatabaseModelFactory.cs

chore: cast COLUMN_DEFAULT value to STRING

---

renovate.json

Configures renovate-bot to also apply updates to branch v3.1.

deps: setup renovate for branch v3.1

---

.github/blunderbuss.yml

Updates auto-assignment of issues

chore: update auto-assignment of issues

---

release-please-config.json

Fixes https://github.com/googleapis/release-please/issues/1690

build: also update the PackageVersion entry in csproj files

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/Google.Cloud.EntityFrameworkCore.Spanner.Tests.csproj
Google.Cloud.EntityFrameworkCore.Spanner/Google.Cloud.EntityFrameworkCore.Spanner.csproj

Bump all Spanner and gRPC dependencies at once.

deps: bump all Spanner and gRPC dependencies

---

.kokoro/requirements.txt

Reverts googleapis/dotnet-spanner-entity-framework#325

Revert "chore(deps): update dependency urllib3 to v2 (main)"

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs

Clean up some warnings in the mock server tests.

chore: cleanup warnings in tests

---

Google.Cloud.EntityFrameworkCore.Spanner.Samples/SampleModel/SampleDataModel.sql
Google.Cloud.EntityFrameworkCore.Spanner.Samples/SampleModel/Venue.cs
Google.Cloud.EntityFrameworkCore.Spanner.Samples/Snippets/CommitTimestampSample.cs
Google.Cloud.EntityFrameworkCore.Spanner.Samples/Snippets/ConcurrencyTokenSample.cs
Google.Cloud.EntityFrameworkCore.Spanner.Samples/Snippets/TimestampSample.cs

Add a column with type JSON to the data model that is used for the samples.

docs: add JSON column to sample data model

---

Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/MigrationTests/MigrationModels/MigrationDbContext.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/MigrationTests/Migrations/20210830082803_Initial.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/MigrationTests/SpannerMigrationTest.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/Model/SpannerSampleDbContext.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/Model/Tracks.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/SampleDataModel.sql
Google.Cloud.EntityFrameworkCore.Spanner.Samples/SampleModel/SampleDataModel.sql
Google.Cloud.EntityFrameworkCore.Spanner.Samples/SampleModel/SpannerSampleDbContext.cs
Google.Cloud.EntityFrameworkCore.Spanner.Samples/SampleModel/Track.cs
Google.Cloud.EntityFrameworkCore.Spanner.Samples/Snippets/DefaultColumnValueSample.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/Migrations/SpannerMigrationSqlGeneratorTest.cs
Google.Cloud.EntityFrameworkCore.Spanner/Migrations/SpannerMigrationsSqlGenerator.cs

Add support for DEFAULT column values in combination with Spanner.

feat: support DEFAULT column values

---

.kokoro/release.sh

ci: We don't need ssh for commitish_override anymore

---

buildrelease.sh

ci: Remove some more SSH leftover

---

.github/workflows/build-and-test.yml
.github/workflows/integration-tests-on-emulator.yml
.github/workflows/integration-tests-on-production.yml
.github/workflows/samples.yml

Update GitHub Actions workflows to use dotnet 8.0.

build: update workflows to use dotnet 8.0

---

.github/release-trigger.yml

The new Kokoro release jobs are multi-scm
See b/393190949

ci: Configure release trigger for multi-scm

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkUsingMutationsMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/MockSpannerServer.cs

The Spanner client now uses inline-begin-transaction. This means that the client includes a BeginTransaction option with the first command in a transaction, instead of executing a separate BeginTransaction RPC. This improves performance for most workloads, and reduces the probability of getting a TransactionOutcomeUnknown error.
Transactions that only write mutations (blind writes) do not benefit from this optimization, as these transactions do not execute any SQL commands that can include the BeginTransaction option. For these transactions, the Spanner client will still execute a separate BeginTransaction RPC.

perf: use inline-begin-transaction

---

Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/Model/Singers.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/QueryTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkSessionLeakMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/MigrationTests/Models/Singers.cs
Google.Cloud.EntityFrameworkCore.Spanner/Migrations/SpannerMigrationsSqlGenerator.cs
Google.Cloud.EntityFrameworkCore.Spanner/Query/Internal/SpannerDateTimeMethodTranslator.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerDateOnlyTypeMapping.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerTypeMappingSource.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/SpannerDate.cs

Add type mapping for the standard DateOnly struct. These are mapped to the Spanner data type DATE.

feat: add DateOnly type mapping

---

Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/Model/Receipt.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/Model/SpannerSampleDbContext.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/Model/TicketSales.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkUsingMutationsMockServerTests.cs

test: use structured object with JSON column
