googleapis/dotnet-spanner-entity-framework

.github/workflows/build-and-test.yml

Disable parallel execution of integration tests on GitHub Actions, as GH otherwise refuses to execute them.

build: do not execute integration tests in parallel

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/Migrations/MigrationSqlGeneratorTestBase.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/Migrations/SpannerMigrationSqlGeneratorTest.cs
Google.Cloud.EntityFrameworkCore.Spanner/Migrations/SpannerMigrationsSqlGenerator.cs

Currently, In Spanner two operation has been perform on column while [updating schema](https://cloud.google.com/spanner/docs/data-definition-language#ddl_syntax).
1. Change Datatype
2. Add `{ OPTIONS ( allow_commit_timestamp = { true | null } ) }` option.

feat: alter column migration support

---

Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/MigrationTests/MigrationModels/AllColType.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/MigrationTests/Migrations/20210324085522_Initial.Designer.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/MigrationTests/Migrations/20210324085522_Initial.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/MigrationTests/Migrations/TestMigrationDbContextModelSnapshot.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/MigrationTests/SpannerMigrationTest.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/Model/TableWithAllColumnTypes.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/QueryTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/SampleDataModel - Emulator.sql
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/SampleDataModel.sql
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/MigrationTests/SampleMigrationDataModel.sql
Google.Cloud.EntityFrameworkCore.Spanner.Tests/Migrations/SpannerHistoryRepositoryTest.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/Migrations/SpannerMigrationSqlGeneratorTest.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/TypeConversionTests.cs
Google.Cloud.EntityFrameworkCore.Spanner/Migrations/Internal/SpannerHistoryRepository.cs
Google.Cloud.EntityFrameworkCore.Spanner/Migrations/SpannerMigrationsSqlGenerator.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerSqlGenerationHelper.cs

In the current implementation while using [spanner reserved keywords](https://cloud.google.com/spanner/docs/lexical#reserved_keywords) as column/table/constraint name it is breaking in migration as well as performing the query on same.
**Step to reproduce:**
Schema:
```C#
public partial class Singers
{
public long SingerId { get; set; }
public string ASC { get; set; }
}
```
Query:
```C#
var db = new MyDbContext();
db.Singers.Add(new Singer
{	
SingerId = 1,
ASC = "Test"
});
db.SaveChanges();
```
Propose implementation is to use **backticks ( ` )** in all the query.

fix: handle spanner reserved keywords

---

Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/MigrationTests/MigrationTestFixture.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/MigrationTests/Migrations/20210324085522_Initial.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/MigrationTests/SpannerMigrationTest.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/xunit.runner.json

The emulator now supports computed columns, as long as the computed column is the last column in the table.
Fixes [this build error](https://github.com/cloudspannerecosystem/dotnet-spanner-entity-framework/pull/72/checks?check_run_id=2202481074).

fix: the emulator now supports computed columns

---

Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/ModelValidationTests/Model/Album.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/ModelValidationTests/Model/InvalidChildEntityDbContext.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/ModelValidationTests/Model/InvalidEntityDbContext.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/ModelValidationTests/Model/ModelValidationTestFixture.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/ModelValidationTests/Model/ModelWithUniqueIndexAsKeyDbContext.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/ModelValidationTests/Model/Singer.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/ModelValidationTests/Model/ValidDbContext.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/ModelValidationTests/ModelValidationTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/NonParallelTestCollection.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkUsingMutationsMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/MigrationTests/GenerateCreateScriptTest.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/Migrations/MigrationSqlGeneratorTestBase.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/Migrations/SpannerHistoryRepositoryTest.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/Migrations/SpannerMigrationSqlGeneratorTest.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/TestUtilities/SpannerTestHelpers.cs
Google.Cloud.EntityFrameworkCore.Spanner/Extensions/Internal/ModelValidationConnectionStringProvider.cs
Google.Cloud.EntityFrameworkCore.Spanner/Extensions/Internal/SpannerModelValidationConnectionProvider.cs
Google.Cloud.EntityFrameworkCore.Spanner/Extensions/SpannerDatabaseFacadeExtensions.cs
Google.Cloud.EntityFrameworkCore.Spanner/Extensions/SpannerDbContextOptionsExtensions.cs
Google.Cloud.EntityFrameworkCore.Spanner/Extensions/SpannerServiceCollectionExtensions.cs
Google.Cloud.EntityFrameworkCore.Spanner/Google.Cloud.EntityFrameworkCore.Spanner.csproj
Google.Cloud.EntityFrameworkCore.Spanner/Infrastructure/Internal/SpannerModelValidator.cs

Adds validation of the entity model that is used against the actual database. The current validation only adds a check for the key that is used for each entity, but the setup could be used for additional validations in the future.
The check for the key that is set on an entity verifies that:
1. The key of the entity corresponds exactly with the columns of the primary key of the table
2. OR the key of the entity corresponds exactly with the columns of another unique not null-filtered index on the table.
This type of validation is not really supported by Entity Framework itself. The built-in model validation is intended to only validate the __model__, and not whether the model corresponds with the database. The support that is added in this PR is therefore limited:
1. The model validator …

feat: validate entity model against database

---

Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/TransactionTests.cs

The current version of the emulator can read `ARRAY<NUMERIC>` columns, so this restriction is no longer needed.

test: enable test assertion for emulator

---

Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/TransactionTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Samples/SampleModel/SampleDataModel.sql
Google.Cloud.EntityFrameworkCore.Spanner.Samples/SampleModel/SpannerSampleDbContext.cs
Google.Cloud.EntityFrameworkCore.Spanner.Samples/Snippets/CommitTimestampSample.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRetriableTransaction.cs
Google.Cloud.EntityFrameworkCore.Spanner/Update/Internal/SpannerModificationCommandBatch .cs
README.md

Propagates an automatically generated commit timestamp to the entity in the current `DbContext`. This removes the requirement to detach and re-fetch an entity to get a newly generated commit timestamp.
Fixes #10

feat: propagate commit timestamp to current DbContext

---

Google.Cloud.EntityFrameworkCore.Spanner/Google.Cloud.EntityFrameworkCore.Spanner.csproj
docs/history.md

Changes in Google.Cloud.EntityFrameworkCore.Spanner version 0.2.0:
- [Commit 6664d8d](https://github.com/googleapis/dotnet-spanner-entity-framework/commit/6664d8d) test: add test to verify the use of DDL batches ([#92](https://github.com/googleapis/dotnet-spanner-entity-framework/pull/92))
- [Commit 68256c9](https://github.com/googleapis/dotnet-spanner-entity-framework/commit/68256c9) chore(deps): update dependency xunit to v2.4.1 ([#97](https://github.com/googleapis/dotnet-spanner-entity-framework/pull/97))
- [Commit e5d6018](https://github.com/googleapis/dotnet-spanner-entity-framework/commit/e5d6018) chore: add renovate.json ([#85](https://github.com/googleapis/dotnet-spanner-entity-framework/pull/85))
- [Commit 85dd134](https://github.com/googleapis/dotnet-spanner-entity-framework/comm …

chore: release EntityFrameworkCore.Spanner v0.2.0

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/MockSpannerServer.cs

A rollback request could clear the _abortNextStatement flag. This would mean that
an async Rollback request could affect a later test case that was using the same
fixture if the Rollback request would be processed after the _abortNextStatement
flag had been set by the following test case.
Fixes #95

test: rollback should not clear the _abortNextStatement flag

---

Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRetriableConnection.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRetriableTransaction.cs

Fixes warnings in PRs about missing `new` keyword for methods that hide a superclass method.

chore: add new keyword for methods that hide a super class method

---

Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/SpannerFixtureBase.cs

Random strings should use Unicode instead of ASCII encoding to ensure that the generated
string is actually random, and not '????'.
Fixes #112

test: use unicode for random strings

---

README.md

We now publish packages to NuGet so there's no need to build these locally.

docs: remove local NuGet pkg instructions

---

Google.Cloud.EntityFrameworkCore.Spanner/Google.Cloud.EntityFrameworkCore.Spanner.csproj
README.md
docs/history.md

Changes in Google.Cloud.EntityFrameworkCore.Spanner version 1.0.0:
- [Commit baee99b](https://github.com/googleapis/dotnet-spanner-entity-framework/commit/baee99b) feat: support single stale reads ([#120](https://github.com/googleapis/dotnet-spanner-entity-framework/pull/120))
- [Commit 429486c](https://github.com/googleapis/dotnet-spanner-entity-framework/commit/429486c) fix: use build instead of revision in version ([#118](https://github.com/googleapis/dotnet-spanner-entity-framework/pull/118))
- [Commit 7bfb5e4](https://github.com/googleapis/dotnet-spanner-entity-framework/commit/7bfb5e4) test: use assembly version instead of hard coded string ([#114](https://github.com/googleapis/dotnet-spanner-entity-framework/pull/114))
- [Commit …

chore: release EntityFrameworkCore.Spanner v1.0.0

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/Google.Cloud.EntityFrameworkCore.Spanner.Tests.csproj
Google.Cloud.EntityFrameworkCore.Spanner.Tests/SpannerConverter.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerDataReaderWithChecksum.cs

Calling DataReader.GetFieldValue<T>(int) could fail if the column was an array and that
array contained at least one null element. This would only happen if all the following
conditions were met:
1. The query was executed as part of a read/write transaction.
2. The default type for the array element type is not nullable (e.g. long, double, SpannerNumeric)
3. The array in the Cloud Spanner table contained at least one NULL element.
Fixes #143

fix: DataReader.GetFieldValue<T> could fail for array types

---

.github/workflows/integration-tests-on-production.yml

Use v0 instead of master, as master is no longer supported.

build: use v0 instead of master

---

.kokoro/requirements.txt

Fixes a missing hash update in the requirements.txt file that failed the release build.

fix: update requirements hash

---

Google.Cloud.EntityFrameworkCore.Spanner/Scaffolding/Internal/SpannerDatabaseModelFactory.cs

this will cause error when run database first migration
Fixes #233 
> It's a good idea to open an issue first for discussion.
- [ V ] Tests pass
- [ X ] Appropriate changes to README are included in PR

fix: missing select column TABLE_NAME in scaffolding

---

Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/MigrationTests/Migrations/20210830082803_Initial.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/MigrationTests/SpannerMigrationTest.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/MigrationTests/MigrationMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/Migrations/SpannerMigrationSqlGeneratorTest.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerJsonTypeMapping.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerStringTypeMapping.cs

Prevent errors when generating string literals by using triple-quoted literals. These allow unescaped newlines and quotes inside the string.
Fixes #273

fix: prevent errors with newlines by using triple-quoted literals

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner/Properties/AssemblyInfo.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerDataReaderWithChecksum.cs

The SpannerDataReaderWithChecksum did not dispose the underlying SpannerDataReader when it was closed/disposed. This caused unnecessary logging to happen that indicated that a session could have been leaked. The failure to close the underlying reader would however not cause a session leak, as the session is managed by the surrounding transaction, which again will return the session to the pool when the transaction is disposed.

fix: dispose the underlying SpannerDataReader

---

Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerReadOnlyTransaction.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRetriableCommand.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRetriableConnection.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRetriableTransaction.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerTransactionBase.cs

Fixes #396
This PR provides the following async method implementations that are missing:
SpannerReadOnlyTransaction.ExecuteDbDataReaderWithRetryAsync
SpannerRetriableCommand.ExecuteDbDataReaderAsync
SpannerRetriableConnection.OpenAsync
SpannerRetriableConnection.CloseAsync
SpannerRetriableTransaction.ExecuteDbDataReaderWithRetryAsync
- [N/A] Appropriate changes to README are included in PR

fix: add missing async methods

---

README.md

The README wrongly stated that decimal could be used for numeric columns. This feature was never added to the underlying Spanner client library, and is therefore also not supported in Entity Framework.

docs: remove decimal from README as supported type

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/AbortedTransactionsTests.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRetriableConnection.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRetriableTransaction.cs

This PR provides the following async method implementations that are missing:
SpannerRetriableConnection.BeginDbTransactionAsync
SpannerRetriableTransaction.CommitAsync
Fixes #408
> It's a good idea to open an issue first for discussion.
- [N/A] Appropriate changes to README are included in PR

fix: add missing BeginDbTransactionAsync and CommitAsync async methods

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkUsingMutationsMockServerTests.cs

Ignore stray RollbackRequests in test, as these are executed async. That means that a previous test could add a RollbackRequest to the collection of requests that a later test sees.
Also cleans up some warnings.
Fixes #416

chore: ignore stray RollbackRequests in test

---

renovate.json

Configure renovate to use `deps:` commit prefix, so new deps trigger a new release.

deps: configure renovate to use deps: prefix

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/AbortedTransactionsTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/MockSpannerServer.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRetriableTransaction.cs

DML statements with a THEN RETURN clause need to be executed using the ExecuteReader method. These were normally not executed in a retry loop, as they were up until now only used for queries. Queries are executed during the first call to Reader#Read(), which meant that a retry loop was not needed for calls to ExecuteReader. DML statements with a THEN RETURN clause are executed directly, and therefore need a retry loop.
This fix adds a retry loop for that, and tests for DML statements with a THEN RETURN clause.

feat: retry DML with THEN RETURN in transactions

---

.kokoro/release.sh

@olavloite I've removed from these scripts some values that you are not using, because you are not publishing docs with docuploader nor running integration tests on release. Can you please confirm all of that? Removing these makes migration easier.
@jskeet Equally, take a look and see if something seems not right. These scripts are originally copied from google-cloud-dotnet but we have diverged over time.
Marking as `do not merge` as I need to coordinate merging of this PR with some CLs. See b/371220760 for more information.

ci: Remove unused values from release scripts

---

Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/QueryTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner/Query/Internal/SpannerInExpression.cs
Google.Cloud.EntityFrameworkCore.Spanner/Query/Internal/SpannerQuerySqlGenerator.cs
Google.Cloud.EntityFrameworkCore.Spanner/Query/Internal/SpannerSqlExpressionFactory.cs
Google.Cloud.EntityFrameworkCore.Spanner/Query/Internal/SpannerSqlNullabilityProcessor.cs

IN queries were automatically translated by EF Core to queries that used `IN (value1, value2, ..., valueN)`. This requires Spanner to re-compile the query for every possible permutation of the list of values.
This change registers a specific SpannerInExpression that is used when a query using a fixed list of values is being generated. These queries are then translated to queries of this form:
`IN UNNEST (@values)`
The `@values` parameter is of type ARRAY.

perf: translate Contains to a parameterized IN query

---

Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/Model/Performances.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/Model/SpannerSampleDbContext.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/SampleDataModel.sql
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerTypeMappingSource.cs

int[], int?[], List<int>, and List<int?> did not have a type mapping for Spanner. This again meant that if they were used to for example filter based on a list of identifiers, that it would be sent to Spanner as a list of literals instead of query parameters. This adds a type mapping for these types to the ARRAY<INT64> type in Spanner.

feat: add type mapping for int arrays and int lists

---

build.sh
buildrelease.sh

The existing scripts had been copied from google-cloud-dotnet and had a lot of unused code for dealing with the release of multiple packages, etc. These are similar to the ones in google-cloudevents-dotnet which is also a single package repository.
See b/393190949

ci: Simplify release and build scripts.

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/Migrations/SpannerMigrationSqlGeneratorTest.cs
Google.Cloud.EntityFrameworkCore.Spanner/Migrations/SpannerMigrationsSqlGenerator.cs

Fixes #510
- [ N/A] Appropriate changes to README are included in PR
Adds parentheses to default values in migrations. I'm not sure about the triple quoting of string literals (see AlterColumnOperation_set_default_value test), but that is the existing implementation of GenerateSqlLiteral for strings

fix: migration default value should be wrapped in parentheses

---

renovate.json

Remove the renovate configuration for the 3.1 branch, as Entity Framework Core 3.1 is no longer supported. See https://learn.microsoft.com/en-us/ef/core/what-is-new/ for the supported versions.

build: remove renovate config for v3.1

---

Google.Cloud.EntityFrameworkCore.Spanner.Samples/Google.Cloud.EntityFrameworkCore.Spanner.Samples.csproj
Google.Cloud.EntityFrameworkCore.Spanner.Samples/SampleModel/SpannerSampleDbContext.cs
Google.Cloud.EntityFrameworkCore.Spanner/Migrations/Internal/SpannerRelationalAnnotationProvider.cs

Adding an annotation for identity generation on a property did not result in an annotation being added to the column definition when a migration was generated.

fix: identity annotations on properties were not generated

---

Google.Cloud.EntityFrameworkCore.Spanner.Tests/MigrationTests/GenerateCreateScriptTest.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/MigrationTests/Migrations/20210309110233_Initial.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/MigrationTests/Models/SpannerMigrationSampleDbContext.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/Migrations/SpannerMigrationSqlGeneratorTest.cs
Google.Cloud.EntityFrameworkCore.Spanner/Migrations/SpannerMigrationsSqlGenerator.cs

Spanner now supports ON DELETE CASCADE actions for foreign keys. This was however not included in the generated migration script is this had been specified in the model or migration.
Fixes #583

fix: add ON DELETE CASCADE for foreign keys

---

README.md

Clarify which versions of Entity Framework are supported by the provider.

docs: clarify support policy

---

Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/Model/SpannerSampleDbContext.cs
Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests/Model/TicketSales.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkUsingMutationsMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerStringTypeMapping.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerTypeMappingSource.cs

Adding a property to an entity with Clr type `string` and ColumnType JSON will now use a type mapping that allows the value to be stored in the database as JSON.
That is, the following is now supported:
```csharp
public class TicketSales
{
public long Id { get; set; }
public string CustomerName { get; set; }
/// <summary>
/// Receipt is stored as a JSON column in the database.
/// </summary>
public string Receipt { get; set; }
}
// ... In the DbContext ...
modelBuilder.Entity<TicketSales>(entity =>
{
entity.Property(e => e.Receipt).HasColumnType("JSON");
});
```
Fixes #592

feat: allow string to be mapped to JSON columns

---

Google.Cloud.EntityFrameworkCore.Spanner.Samples/Snippets/IsolationLevelSample.cs
Google.Cloud.EntityFrameworkCore.Spanner.Tests/EntityFrameworkMockServerTests.cs
Google.Cloud.EntityFrameworkCore.Spanner/Storage/Internal/SpannerRetriableConnection.cs

Spanner now supports the isolation levels RepeatableRead and Serializable. This change adds support for setting these isolation levels in Entity Framework.

feat: support isolation levels
